apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-identifiants
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-identifiants
  template:
    metadata:
      labels:
        app: gestion-identifiants
    spec:
      containers:
      - name: gestion-identifiants
        image: sankara973/gestion-identifiants:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          value: identifiants
        - name: DB_USER
          value: admin
        - name: DB_PASS
          value: password123
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-identifiants
spec:
  selector:
    app: gestion-identifiants
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer