apiVersion: v2
name: gestion-identifiants
description: Gestionnaire d'identifiants sécurisé - Flask, PostgreSQL, Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Boureima SANKARA
    email: brsankara7@gmail.com